<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250422164154 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Создаёт таблицу статистики по заданиям студентов';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE student_stats (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, student_id BIGINT NOT NULL, course_id BIGINT NOT NULL, module_id BIGINT NOT NULL, lesson_id BIGINT NOT NULL, task_id BIGINT NOT NULL, skill_id BIGINT NOT NULL, score INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DF701E37CB944F1A ON student_stats (student_id)');
        $this->addSql('CREATE INDEX IDX_DF701E37591CC992 ON student_stats (course_id)');
        $this->addSql('CREATE INDEX IDX_DF701E37AFC2B591 ON student_stats (module_id)');
        $this->addSql('CREATE INDEX IDX_DF701E37CDF80196 ON student_stats (lesson_id)');
        $this->addSql('CREATE INDEX IDX_DF701E378DB60186 ON student_stats (task_id)');
        $this->addSql('CREATE INDEX IDX_DF701E375585C142 ON student_stats (skill_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DF701E37CB944F1A5585C142 ON student_stats (student_id, skill_id)');
        $this->addSql('ALTER TABLE student_stats ADD CONSTRAINT FK_DF701E37CB944F1A FOREIGN KEY (student_id) REFERENCES student (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_stats ADD CONSTRAINT FK_DF701E37591CC992 FOREIGN KEY (course_id) REFERENCES course (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_stats ADD CONSTRAINT FK_DF701E37AFC2B591 FOREIGN KEY (module_id) REFERENCES module (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_stats ADD CONSTRAINT FK_DF701E37CDF80196 FOREIGN KEY (lesson_id) REFERENCES lesson (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_stats ADD CONSTRAINT FK_DF701E378DB60186 FOREIGN KEY (task_id) REFERENCES task (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_stats ADD CONSTRAINT FK_DF701E375585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE student_stats DROP CONSTRAINT FK_DF701E37CB944F1A');
        $this->addSql('ALTER TABLE student_stats DROP CONSTRAINT FK_DF701E37591CC992');
        $this->addSql('ALTER TABLE student_stats DROP CONSTRAINT FK_DF701E37AFC2B591');
        $this->addSql('ALTER TABLE student_stats DROP CONSTRAINT FK_DF701E37CDF80196');
        $this->addSql('ALTER TABLE student_stats DROP CONSTRAINT FK_DF701E378DB60186');
        $this->addSql('ALTER TABLE student_stats DROP CONSTRAINT FK_DF701E375585C142');
        $this->addSql('DROP TABLE student_stats');
    }
}
