<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250422145934 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Создаёт таблицу заданий студентов';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE student_task (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, student_id BIGINT DEFAULT NULL, task_id BIGINT DEFAULT NULL, task_status VARCHAR(255) NOT NULL, task_min_requirements BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6D5DA0FDCB944F1A ON student_task (student_id)');
        $this->addSql('CREATE INDEX IDX_6D5DA0FD8DB60186 ON student_task (task_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6D5DA0FDCB944F1A8DB60186 ON student_task (student_id, task_id)');
        $this->addSql('ALTER TABLE student_task ADD CONSTRAINT FK_6D5DA0FDCB944F1A FOREIGN KEY (student_id) REFERENCES student (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_task ADD CONSTRAINT FK_6D5DA0FD8DB60186 FOREIGN KEY (task_id) REFERENCES task (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE student_task DROP CONSTRAINT FK_6D5DA0FDCB944F1A');
        $this->addSql('ALTER TABLE student_task DROP CONSTRAINT FK_6D5DA0FD8DB60186');
        $this->addSql('DROP TABLE student_task');
    }
}
