<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250226090358 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Генерирует таблицы: модули, курсы';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE course (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, manager VARCHAR(255) DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE module (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, course_id BIGINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX module__course_id__ind ON module (course_id)');
        $this->addSql('ALTER TABLE module ADD CONSTRAINT module__course_id_fk FOREIGN KEY (course_id) REFERENCES course (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lesson ADD module_id BIGINT DEFAULT NULL');
        $this->addSql('ALTER TABLE lesson ADD CONSTRAINT lesson__module_id_fk FOREIGN KEY (module_id) REFERENCES module (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX lesson__module_id__ind ON lesson (module_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE module DROP CONSTRAINT module__course_id_fk');
        $this->addSql('DROP TABLE course');
        $this->addSql('ALTER TABLE lesson DROP CONSTRAINT lesson__module_id_fk');
        $this->addSql('DROP TABLE module');
        $this->addSql('DROP INDEX lesson__module_id__ind');
        $this->addSql('ALTER TABLE lesson DROP module_id');
    }
}
