# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Application\Security\AuthService:
        arguments:
            $tokenTTL: '%env(JWT_TTL_SEC)%'

    App\Infrastructure\Bus\RabbitMqBus:
        calls:
            - [ 'registerProducer', [ !php/enum App\Infrastructure\Bus\AmqpExchangeEnum::AddStudentStats, '@old_sound_rabbit_mq.add_student_stats_producer' ] ]
            - [ 'registerProducer', [ !php/enum App\Infrastructure\Bus\AmqpExchangeEnum::InvalidateStatsCache, '@old_sound_rabbit_mq.invalidate_stats_cache_producer' ] ]

    redis_client:
        class: Redis
        factory: Symfony\Component\Cache\Adapter\RedisAdapter::createConnection
        arguments:
            - '%env(REDIS_DSN)%'

    redis_tag_aware_adapter:
        class: Symfony\Component\Cache\Adapter\RedisTagAwareAdapter
        arguments:
            - '@redis_client'
            - 'my_app'

    App\Infrastructure\Repository\StudentStatsRepositoryCacheDecorator:
        arguments:
            $tagAwareCache: '@redis_tag_aware_adapter'

    App\Infrastructure\Service\StudentStatsCacheService:
        arguments:
            $tagAwareCache: '@redis_tag_aware_adapter'
