[program:add_student_stats]
command=php -dmemory_limit=1G /app/bin/console rabbitmq:consumer -m 100 add_student_stats --env=dev -vv
process_name=add_student_stats_%(process_num)02d
numprocs=1
directory=/tmp
autostart=true
autorestart=true
startsecs=3
startretries=10
user=www-data
redirect_stderr=false
stdout_logfile=/app/var/log/supervisor.add_student_stats.out.log
stdout_capture_maxbytes=1MB
stderr_logfile=/app/var/log/supervisor.add_student_stats.error.log
stderr_capture_maxbytes=1MB

[program:invalidate_stats_cache]
command=php -dmemory_limit=1G /app/bin/console rabbitmq:consumer -m 100 invalidate_stats_cache --env=dev -vv
process_name=invalidate_stats_cache_%(process_num)02d
numprocs=1
directory=/tmp
autostart=true
autorestart=true
startsecs=3
startretries=10
user=www-data
redirect_stderr=false
stdout_logfile=/app/var/log/supervisor.invalidate_stats_cache.out.log
stdout_capture_maxbytes=1MB
stderr_logfile=/app/var/log/supervisor.invalidate_stats_cache.error.log
stderr_capture_maxbytes=1MB
